ffin-url: https://bankffin.kz
update-cron: '0 */15 * ? * *'
bot:
  name: FFinCurrencyBot
  token: ${BOT_TOKEN:test-token}

logging:
  level:
    kz.asmirnov.ffin.ffincurrencynotifier.ffinclient.logging.logging.LoggingInterceptor: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: info
spring:
  sql:
    init:
      mode: always
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/asmirnov}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
