ffin-url: https://bankffin.kz
update-cron: '0 */5 * ? * *'
bot:
  name: FFinCurrencyBot
  token: ${BOT_TOKEN:test-token}

logging:
  level:
    kz.asmirnov.ffin.ffincurrencynotifier.logging.LoggingInterceptor: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: info
