ffin-url: https://bankffin.kz
update-cron: '0 */5 * ? * *'
bot:
  name: FFinCurrencyBot
  token: 6267723513:AAFPAw6gJfrcGZydCgMey-IbvR2VSNfro7k

logging:
  level:
    kz.asmirnov.ffin.ffincurrencynotifier.logging.LoggingInterceptor: DEBUG
