micronaut:
  server:
    port: 8080
  application:
    name: ffin-currency-bot
  http:
    services:
      ffin:
        url: https://bankffin.kz

datasources:
  default:
    url: jdbc:${DATABASE_URL:`postgresql://localhost:5432/a.smirnov19`}
    dialect: POSTGRES
    driverClassName: org.postgresql.Driver
    minPoolSize: 1

jpa:
  default:
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: validate
        show_sql: false

flyway:
  datasources:
    default:
      enabled: true

ffin-url: https://bankffin.kz
update-cron: '0 */15 * ? * *'
bot:
  name: FFinCurrencyBot
  token: ${BOT_TOKEN:tst}
